# Generated by Django 5.0 on 2024-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('anel', 'Anel'), ('brinco', 'Brinco'), ('colar', 'Colar'), ('pulseira', 'Pulseira'), ('pingente', 'Pingente'), ('alianca', 'Aliança'), ('relogio', 'Relógio'), ('outro', 'Outro')], default='outro', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG'), ('u', 'Único')], default='u', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
